# Generated by Django 4.0.6 on 2022-08-09 03:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
