# Generated by Django 4.0.6 on 2022-08-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='type',
            new_name='is_type',
        ),
    ]
