# Generated by Django 4.0.6 on 2022-08-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateField(),
        ),
    ]
