# Generated by Django 4.0.6 on 2022-08-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_journal_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='is_type',
            new_name='category',
        ),
    ]
