# Generated by Django 4.0.6 on 2022-08-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_rename_is_type_journal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalimage',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='journalstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
