# Generated by Django 4.0.6 on 2022-08-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_assignimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date accepted'),
        ),
    ]
