# Generated by Django 4.0.6 on 2022-08-15 03:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_alter_assign_accepted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='assign',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
