# Generated by Django 4.0.6 on 2022-08-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0005_alter_assignimage_options_alter_assignstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignStatus', to='assign.assignstatus'),
        ),
    ]
