# Generated by Django 4.0.6 on 2022-08-20 18:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0006_alter_assign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', ckeditor.fields.RichTextField()),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.assign')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.assignstatus')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
            },
        ),
    ]
