# Generated by Django 4.1 on 2022-08-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assign", "0009_alter_assignprogress_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignprogress",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
