# Generated by Django 4.0.6 on 2022-09-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0010_alter_assignprogress_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignprogress',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
