# Generated by Django 4.0.6 on 2022-08-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_no', models.CharField(max_length=255)),
                ('send_from', models.CharField(max_length=255)),
                ('doc_no', models.CharField(max_length=255)),
                ('urgency', models.CharField(choices=[('ปกติ', 'ปกติ'), ('ด่วน', 'ด่วน'), ('ด่วนมาก', 'ด่วนมาก'), ('ด่วนที่สุด', 'ด่วนที่สุด')], default='ปกติ', max_length=255)),
                ('doc_type', models.CharField(choices=[('ปฏิบัติ', 'ปฏิบัติ'), ('เพื่อทราบ', 'เพื่อทราบ')], default='เพื่อทราบ', max_length=255)),
                ('title', models.TextField()),
                ('doc_date', models.DateField()),
                ('receive_date', models.DateTimeField(auto_now_add=True)),
                ('set_in', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('รอการปฎิบัติ', 'รอการปฏิบัติ'), ('รับ', 'รับ'), ('ดำเนินการแล้ว', 'ดำเนินการแล้ว')], default='รับ', max_length=255)),
                ('assigned_group', models.ManyToManyField(blank=True, related_name='assignedGroup', to='account.sector')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedUser', to='account.profile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_no', models.CharField(max_length=255)),
                ('send_out', models.CharField(blank=True, max_length=255)),
                ('doc_no', models.CharField(max_length=255)),
                ('urgency', models.CharField(choices=[('ปกติ', 'ปกติ'), ('ด่วน', 'ด่วน'), ('ด่วนมาก', 'ด่วนมาก'), ('ด่วนที่สุด', 'ด่วนที่สุด')], default='ปกติ', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('doc_date', models.DateTimeField()),
                ('out_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_send', to='account.sector')),
                ('ref_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_doc', to='document.inbox')),
                ('send_to', models.ManyToManyField(blank=True, related_name='receiver', to='account.sector')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=document.models.get_file_name_outbox)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.outbox')),
            ],
        ),
        migrations.CreateModel(
            name='InboxFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=document.models.get_file_name_inbox)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.inbox')),
            ],
        ),
    ]
