# Generated by Django 4.0.6 on 2022-08-25 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_no', models.CharField(max_length=255)),
                ('send_from', models.CharField(max_length=255)),
                ('doc_no', models.CharField(max_length=255)),
                ('urgency', models.CharField(choices=[('ปกติ', 'ปกติ'), ('ด่วน', 'ด่วน'), ('ด่วนมาก', 'ด่วนมาก'), ('ด่วนที่สุด', 'ด่วนที่สุด')], default='ปกติ', max_length=255)),
                ('doc_type', models.CharField(choices=[('ปฏิบัติ', 'ปฏิบัติ'), ('เพื่อทราบ', 'เพื่อทราบ')], default='เพื่อทราบ', max_length=255)),
                ('title', models.TextField()),
                ('doc_date', models.DateField()),
                ('receive_date', models.DateTimeField(auto_now_add=True)),
                ('set_in', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('รอการปฎิบัติ', 'รอการปฏิบัติ'), ('รับ', 'รับ')], default='รับ', max_length=255)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
