# Generated by Django 4.1 on 2022-08-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("document", "0002_inboxfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignedGroup",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="inbox",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignedUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
