# Generated by Django 4.1 on 2022-08-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("document", "0004_alter_inbox_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="assigned_group",
        ),
        migrations.AddField(
            model_name="inbox",
            name="assigned_group",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="assignedGroup", to="account.sector"
            ),
        ),
    ]
