# Generated by Django 4.0.6 on 2022-08-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetType',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='category',
        ),
    ]
