# Generated by Django 4.0.6 on 2022-08-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_request_able'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
