# Generated by Django 4.0.6 on 2022-08-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0004_alter_announce_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcefile',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='announceimage',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='announcestatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
